"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Sequence
from datetime import date, datetime, time
from typing import Any
from typing_extensions import Self
from wtforms.fields.core import Field, _Filter, _FormT, _Validator, _Widget
from wtforms.form import BaseForm
from wtforms.meta import DefaultMeta, _SupportsGettextAndNgettext

class DateTimeField(Field):
    format: list[str]
    strptime_format: list[str]
    data: datetime | None
    default: datetime | Callable[[], datetime] | None
    def __init__(
        self,
        label: str | None = ...,
        validators: tuple[_Validator[_FormT, Self], ...] | list[Any] | None = ...,
        format: str | list[str] = ...,
        *,
        filters: Sequence[_Filter] = ...,
        description: str = ...,
        id: str | None = ...,
        default: datetime | Callable[[], datetime] | None = ...,
        widget: _Widget[Self] | None = ...,
        render_kw: dict[str, Any] | None = ...,
        name: str | None = ...,
        _form: BaseForm | None = ...,
        _prefix: str = ...,
        _translations: _SupportsGettextAndNgettext | None = ...,
        _meta: DefaultMeta | None = ...
    ) -> None: ...

class DateField(DateTimeField):
    data: date | None
    default: date | Callable[[], date] | None
    def __init__(
        self,
        label: str | None = ...,
        validators: tuple[_Validator[_FormT, Self], ...] | list[Any] | None = ...,
        format: str | list[str] = ...,
        *,
        filters: Sequence[_Filter] = ...,
        description: str = ...,
        id: str | None = ...,
        default: date | Callable[[], date] | None = ...,
        widget: _Widget[Self] | None = ...,
        render_kw: dict[str, Any] | None = ...,
        name: str | None = ...,
        _form: BaseForm | None = ...,
        _prefix: str = ...,
        _translations: _SupportsGettextAndNgettext | None = ...,
        _meta: DefaultMeta | None = ...
    ) -> None: ...

class TimeField(DateTimeField):
    data: time | None
    default: time | Callable[[], time] | None
    def __init__(
        self,
        label: str | None = ...,
        validators: tuple[_Validator[_FormT, Self], ...] | list[Any] | None = ...,
        format: str | list[str] = ...,
        *,
        filters: Sequence[_Filter] = ...,
        description: str = ...,
        id: str | None = ...,
        default: time | Callable[[], time] | None = ...,
        widget: _Widget[Self] | None = ...,
        render_kw: dict[str, Any] | None = ...,
        name: str | None = ...,
        _form: BaseForm | None = ...,
        _prefix: str = ...,
        _translations: _SupportsGettextAndNgettext | None = ...,
        _meta: DefaultMeta | None = ...
    ) -> None: ...

class MonthField(DateField):
    def __init__(
        self,
        label: str | None = ...,
        validators: tuple[_Validator[_FormT, Self], ...] | list[Any] | None = ...,
        format: str | list[str] = ...,
        *,
        filters: Sequence[_Filter] = ...,
        description: str = ...,
        id: str | None = ...,
        default: time | Callable[[], time] | None = ...,
        widget: _Widget[Self] | None = ...,
        render_kw: dict[str, Any] | None = ...,
        name: str | None = ...,
        _form: BaseForm | None = ...,
        _prefix: str = ...,
        _translations: _SupportsGettextAndNgettext | None = ...,
        _meta: DefaultMeta | None = ...
    ) -> None: ...

class WeekField(DateField):
    def __init__(
        self,
        label: str | None = ...,
        validators: tuple[_Validator[_FormT, Self], ...] | list[Any] | None = ...,
        format: str | list[str] = ...,
        *,
        filters: Sequence[_Filter] = ...,
        description: str = ...,
        id: str | None = ...,
        default: time | Callable[[], time] | None = ...,
        widget: _Widget[Self] | None = ...,
        render_kw: dict[str, Any] | None = ...,
        name: str | None = ...,
        _form: BaseForm | None = ...,
        _prefix: str = ...,
        _translations: _SupportsGettextAndNgettext | None = ...,
        _meta: DefaultMeta | None = ...
    ) -> None: ...

class DateTimeLocalField(DateTimeField):
    def __init__(
        self,
        label: str | None = ...,
        validators: tuple[_Validator[_FormT, Self], ...] | list[Any] | None = ...,
        format: str | list[str] = ...,
        *,
        filters: Sequence[_Filter] = ...,
        description: str = ...,
        id: str | None = ...,
        default: time | Callable[[], time] | None = ...,
        widget: _Widget[Self] | None = ...,
        render_kw: dict[str, Any] | None = ...,
        name: str | None = ...,
        _form: BaseForm | None = ...,
        _prefix: str = ...,
        _translations: _SupportsGettextAndNgettext | None = ...,
        _meta: DefaultMeta | None = ...
    ) -> None: ...
