"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Iterable, Iterator
from typing import Any, Generic, TypeVar
from wtforms.fields.core import Field, UnboundField, _FormT, _Validator, _Widget
from wtforms.form import BaseForm
from wtforms.meta import DefaultMeta, _SupportsGettextAndNgettext

_BoundFieldT = TypeVar("_BoundFieldT", bound=Field)

class FieldList(Field, Generic[_BoundFieldT]):
    unbound_field: UnboundField[_BoundFieldT]
    min_entries: int
    max_entries: int | None
    last_index: int
    entries: list[_BoundFieldT]
    object_data: Iterable[Any]
    def __init__(
        self: FieldList[_BoundFieldT],
        unbound_field: UnboundField[_BoundFieldT] | _BoundFieldT,
        label: str | None = ...,
        validators: tuple[_Validator[_FormT, _BoundFieldT], ...]
        | list[Any]
        | None = ...,
        min_entries: int = ...,
        max_entries: int | None = ...,
        separator: str = ...,
        default: Iterable[Any] | Callable[[], Iterable[Any]] = ...,
        *,
        description: str = ...,
        id: str | None = ...,
        widget: _Widget[FieldList[Any]] | None = ...,
        render_kw: dict[str, Any] | None = ...,
        name: str | None = ...,
        _form: BaseForm | None = ...,
        _prefix: str = ...,
        _translations: _SupportsGettextAndNgettext | None = ...,
        _meta: DefaultMeta | None = ...
    ) -> None: ...
    def append_entry(self, data: Any = ...) -> _BoundFieldT: ...
    def pop_entry(self) -> _BoundFieldT: ...
    def __iter__(self) -> Iterator[_BoundFieldT]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> _BoundFieldT: ...
    @property
    def data(self) -> list[Any]: ...
