"""
This type stub file was generated by pyright.
"""

__all__ = ("Translations", "translations")

class Translations:
    def gettext(self, string):  # -> Any:
        ...
    def ngettext(self, singular, plural, n):  # -> Any:
        ...

translations = ...
