"""
This type stub file was generated by pyright.
"""

from wtforms.fields import Field

__all__ = ["RecaptchaField"]

class RecaptchaField(Field):
    widget = ...
    recaptcha_error = ...
    def __init__(self, label=..., validators=..., **kwargs) -> None: ...
