"""
This type stub file was generated by pyright.
"""

RECAPTCHA_VERIFY_SERVER_DEFAULT = ...
RECAPTCHA_ERROR_CODES = ...
__all__ = ["Recaptcha"]

class Recaptcha:
    """Validates a ReCaptcha."""

    def __init__(self, message=...) -> None: ...
    def __call__(self, form, field):  # -> Literal[True] | None:
        ...
